### PR TITLE
File cleaner created and working on both MacOS and Windows

### PR DESCRIPTION
**Pull request by AlexisLasselin**
# Content of this pull request

This pull request contains a functional and definitive version of the file named `fileCleaner.c` and some others file not completely done such as `main.c` that must read a file and execute the assembly or `fileReader.c` that only read a file and print it in the terminal.

## How to run it

You need to build your file by running the following command in the terminal:

> `gcc fileCleaner.c -o fileCleaner`

Once you're able to see a executable file named fileCleaner, go back in your terminal and run the following command:

**On Windows**
> `.\fileCleaner.exe .\test.asm2`

**On MacOS**
> `./fileCleaner test.asm2`

`test.asm2` is a text file containing our assembly code with comments and blank lines.

`testClean.asm2` is the file created with the execution of the built file. It contains the same text as `test.asm2` without the blank lines and comment, keeping only the instructions.

### CODE REVIEW

**Review by thomas-planchard — APPROVED** [review]
LGFM 👍

**Comment by AlexisLasselin** [comment]
FIles edtited to be more readable

**Comment by AlexisLasselin** [comment]
Synthax rules adapted

**Review by Clementine951 — APPROVED** [review]
Looks good

**Pull request merged**
