### PR TITLE
Addition of functional specification version 1 in main

### PR DESCRIPTION
**Pull request by HiNett**
I'm asking you in this pull request to check the information given, and to validate whether it's appropriate and valid so that we can import our Specifications function into the main branch.

### CODE REVIEW

**Review by AlexisLasselin — COMMENTED** [review]
Everything looks good for me

**Review by Clementine951 — APPROVED** [review]
Looks good

**Review by thomas-planchard — APPROVED** [review]
LGFM 👍

**Review by NanaChocolat — APPROVED** [review]
Everything looks good for me.

**Pull request merged**
