### PR TITLE
First Documents Created / Project Charter / Functional / Technical

### PR DESCRIPTION
**Pull request by thomas-planchard**
Create the Functional Specification Document, and let it empty.
Create the Project Charter document.

### CODE REVIEW

**Review by Clementine951 — DISMISSED** [review]

**Review by HiNett — CHANGES_REQUESTED** [review]
Tomorrow we'll be holding a meeting to assign tasks. The Project Charter RACI is not complete at the moment, so I'll validate the Pull Request tomorrow, once the necessary changes to the RACI have been made.

**Comment by Clementine951** [comment]
- [x] Remove the “Creation date” and the “Last update”

GitHub already gives these information, there is no need to add them.
I’ve already got this kind of feedback on an old document.

- [x] What are standard libraries?

This needs to be checked with the client. 
As it’s the project charter, it can be ok because we will use this doc to validate our project idea with the client.

- [x] The RACI matrix is empty.

We will complete it during the meeting on Thursday 11. 

- [x] For deliverables, there are more than that.

You can find them on the project roles v2 document on the Slack server.

**Review by HiNett — COMMENTED** [review]
The RACI are still missing, and we are waiting for this evening's meeting to complete them.

**Review by HiNett — APPROVED** [review]
The meeting having taken place, and the RACI having been validated, I accept the Pull Request for this document in the main branch.

**Review by thomas-planchard — COMMENTED** [review]
LGFM 👍

**Review by AlexisLasselin — APPROVED** [review]
Everything is good for me

**Pull request merged**
